# Generated by Django 4.1.5 on 2023-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_places_package_places_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
